### ISSUE TITLE
Overflow evaluating the requirement, Bevy 0.12.1

### ISSUE THREAD

**Issue by zand** [devildahu/bevy_mod_component_mirror#6]
Worked fine with Bevy 0.12.0 but now fails to compile ever since Bevy 0.12.1 was released.

```Compiling bevy_mod_component_mirror v0.11.0
error[E0275]: overflow evaluating the requirement `CompoundShapeElement: bevy::prelude::FromReflect`
  --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:24:17
   |
24 | #[derive(Clone, Reflect, Default, Component)]
   |                 ^^^^^^^
   |
   = note: required for `std::vec::Vec<CompoundShapeElement>` to implement `bevy::prelude::FromReflect`
note: required for `collider::Compound` to implement `bevy::prelude::Reflect`
  --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:32:17
   |
32 | #[derive(Clone, Reflect, Component)]
   |                 ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
33 | #[reflect(Default)]
34 | pub struct Compound(Vec<CompoundShapeElement>);
   |            ^^^^^^^^
note: required for `collider::Shape` to implement `TypePath`
  --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:66:17
   |
66 | #[derive(Clone, Reflect)]
   |                 ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
...
69 | pub enum Shape {
   |          ^^^^^
   = note: 1 redundant requirement hidden
   = note: required for `ColliderMirror` to implement `TypePath`
   = help: see issue #48214
   = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `collider::Compound: bevy::prelude::Reflect`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:32:17
    |
32  | #[derive(Clone, Reflect, Component)]
    |                 ^^^^^^^
    |
note: required for `collider::Shape` to implement `TypePath`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:66:17
    |
66  | #[derive(Clone, Reflect)]
    |                 ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
...
69  | pub enum Shape {
    |          ^^^^^
note: required for `ColliderMirror` to implement `bevy::prelude::FromReflect`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:123:17
    |
123 | #[derive(Clone, Reflect, Component, Default)]
    |                 ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
124 | #[reflect(Default)]
125 | pub struct ColliderMirror {
    |            ^^^^^^^^^^^^^^
    = note: 2 redundant requirements hidden
    = note: required for `std::vec::Vec<CompoundShapeElement>` to implement `TypePath`
    = help: see issue #48214
    = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `collider::Shape: TypePath`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:66:17
    |
66  | #[derive(Clone, Reflect)]
    |                 ^^^^^^^
    |
note: required for `ColliderMirror` to implement `bevy::prelude::FromReflect`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:123:17
    |
123 | #[derive(Clone, Reflect, Component, Default)]
    |                 ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
124 | #[reflect(Default)]
125 | pub struct ColliderMirror {
    |            ^^^^^^^^^^^^^^
    = note: 2 redundant requirements hidden
    = note: required for `std::vec::Vec<CompoundShapeElement>` to implement `bevy::prelude::FromReflect`
note: required for `collider::Compound` to implement `TypePath`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:32:17
    |
32  | #[derive(Clone, Reflect, Component)]
    |                 ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
33  | #[reflect(Default)]
34  | pub struct Compound(Vec<CompoundShapeElement>);
    |            ^^^^^^^^
    = help: see issue #48214
    = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `ColliderMirror: bevy::prelude::FromReflect`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:109:22
    |
109 | impl FromReflect for Shape {
    |                      ^^^^^
    |
note: required for `CompoundShapeElement` to implement `bevy::prelude::FromReflect`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:24:17
    |
24  | #[derive(Clone, Reflect, Default, Component)]
    |                 ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
25  | #[reflect(Default)]
26  | pub(super) struct CompoundShapeElement {
    |                   ^^^^^^^^^^^^^^^^^^^^
    = note: 1 redundant requirement hidden
    = note: required for `std::vec::Vec<CompoundShapeElement>` to implement `bevy::prelude::FromReflect`
note: required for `collider::Compound` to implement `bevy::prelude::Reflect`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:32:17
    |
32  | #[derive(Clone, Reflect, Component)]
    |                 ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
33  | #[reflect(Default)]
34  | pub struct Compound(Vec<CompoundShapeElement>);
    |            ^^^^^^^^
    = note: 1 redundant requirement hidden
    = note: required for `collider::Shape` to implement `bevy::prelude::Reflect`
note: required by a bound in `bevy::prelude::FromReflect`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_reflect-0.12.1/src/from_reflect.rs:24:24
    |
24  | pub trait FromReflect: Reflect + Sized {
    |                        ^^^^^^^ required by this bound in `FromReflect`
    = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `ColliderMirror: bevy::prelude::FromReflect`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:123:17
    |
123 | #[derive(Clone, Reflect, Component, Default)]
    |                 ^^^^^^^
    |
note: required for `CompoundShapeElement` to implement `bevy::prelude::FromReflect`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:24:17
    |
24  | #[derive(Clone, Reflect, Default, Component)]
    |                 ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
25  | #[reflect(Default)]
26  | pub(super) struct CompoundShapeElement {
    |                   ^^^^^^^^^^^^^^^^^^^^
    = note: 1 redundant requirement hidden
    = note: required for `std::vec::Vec<CompoundShapeElement>` to implement `bevy::prelude::FromReflect`
note: required for `collider::Compound` to implement `bevy::prelude::Reflect`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:32:17
    |
32  | #[derive(Clone, Reflect, Component)]
    |                 ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
33  | #[reflect(Default)]
34  | pub struct Compound(Vec<CompoundShapeElement>);
    |            ^^^^^^^^
note: required for `collider::Shape` to implement `TypePath`
   --> /home/zand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_component_mirror-0.11.0/src/rapier_mirrors/collider.rs:66:17
    |
66  | #[derive(Clone, Reflect)]
    |                 ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
...
69  | pub enum Shape {
    |          ^^^^^
    = help: see issue #48214
    = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0275`.
